# Generated by Django 5.0.1 on 2024-01-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_usuario_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
