# Generated by Django 5.0.1 on 2024-01-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_remove_usuario_contrasena_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
