# Generated by Django 5.0.1 on 2024-01-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_transcripcion_traduccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcripcion',
            new_name='Transcripcion_New',
        ),
    ]
